# Generated by Django 5.2.11 on 2026-03-04 02:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PACK10', 'Pack 10 Clases'), ('REDUCIDO', 'Pack Reducido (2–9 clases)'), ('SUELTA', 'Clase Suelta'), ('PRUEBA', 'Clase de Prueba'), ('PRIVADA', 'Clase Privada')], max_length=20)),
                ('frecuencia', models.CharField(blank=True, choices=[('LMV', 'Lunes – Miércoles – Viernes'), ('LM', 'Lunes – Miércoles'), ('MJ', 'Martes – Jueves')], max_length=3)),
                ('hora', models.PositiveSmallIntegerField(help_text='Hora de inicio (8, 9, 10…)')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('cantidad', models.PositiveSmallIntegerField(default=10)),
                ('precio_total', models.PositiveIntegerField(editable=False)),
                ('estado', models.CharField(choices=[('PENDIENTE_PAGO', 'Pendiente de pago'), ('ACTIVO', 'Activo'), ('COMPLETADO', 'Completado'), ('CONGELADO', 'Congelado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE_PAGO', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('alumna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.PositiveSmallIntegerField()),
                ('numero', models.PositiveSmallIntegerField(help_text='Clase nº dentro del pack (1 a 10)')),
                ('estado', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('COMPLETADA', 'Completada'), ('AUSENTE', 'Ausente sin aviso'), ('RECUPERAR', 'Pendiente recuperación'), ('RECUPERADA', 'Recuperada'), ('CONGELADA', 'Congelada'), ('CANCELADA', 'Cancelada por el centro')], default='PROGRAMADA', max_length=20)),
                ('es_recupero', models.BooleanField(default=False)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='reservas.pack')),
                ('sesion_orig', models.ForeignKey(blank=True, help_text='Sesión original que se recupera', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recuperaciones', to='reservas.sesion')),
            ],
            options={
                'ordering': ['fecha', 'hora'],
                'unique_together': {('fecha', 'hora', 'pack')},
            },
        ),
    ]
