# Generated by Django 5.2.11 on 2026-03-21 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_pack_sesion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='tipo',
            field=models.CharField(choices=[('PACK10', 'Pack 10 Clases'), ('REDUCIDO', 'Pack Reducido (2–9 clases)'), ('SUELTA', 'Clase Suelta'), ('PRUEBA', 'Clase de Prueba'), ('PRIVADA', 'Clase Privada'), ('BB_FULL', 'Body Balance Mensualidad'), ('BB_SEMANAL', 'Body Balance Clase Semanal')], max_length=20),
        ),
    ]
