# Generated by Django 5.2.11 on 2026-03-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_alter_pack_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado')])),
                ('hora', models.PositiveSmallIntegerField()),
                ('tipo', models.CharField(choices=[('PL', 'Pilates Grupal'), ('PV', 'Pilates Privada'), ('BDB', 'Body Balance'), ('TEST', 'Clase de Prueba')], max_length=4)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['hora', 'dia'],
                'unique_together': {('dia', 'hora', 'tipo')},
            },
        ),
    ]
