# Generated by Django 5.2.11 on 2026-03-23 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_configuraciongeneral'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=50, unique=True)),
                ('valor', models.PositiveIntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
