# Generated by Django 5.2.11 on 2026-03-29 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_configuracionprecio'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion',
            name='marcada_ausente_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
