# Generated by Django 5.2.11 on 2026-04-14 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0007_sesion_marcada_ausente_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='hora_dia1',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Hora día 1 (Lun o Mar)', null=True),
        ),
        migrations.AddField(
            model_name='pack',
            name='hora_dia2',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Hora día 2 (Mié o Jue)', null=True),
        ),
        migrations.AddField(
            model_name='pack',
            name='hora_dia3',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Hora día 3 (Vie) — solo LMV', null=True),
        ),
        migrations.AlterField(
            model_name='pack',
            name='hora',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Hora única (para productos no-pack)', null=True),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='numero',
            field=models.PositiveSmallIntegerField(help_text='Clase nº dentro del pack'),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='sesion_orig',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recuperaciones', to='reservas.sesion'),
        ),
    ]
