# Generated by Django 5.2.11 on 2026-04-26 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0008_pack_hora_dia1_pack_hora_dia2_pack_hora_dia3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='hora_dia4',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Hora día 4', null=True),
        ),
        migrations.AlterField(
            model_name='pack',
            name='frecuencia',
            field=models.CharField(blank=True, help_text='Días elegidos, ej: 0,2,5 (Lun,Mié,Sáb)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pack',
            name='hora_dia1',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Hora día 1', null=True),
        ),
        migrations.AlterField(
            model_name='pack',
            name='hora_dia2',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Hora día 2', null=True),
        ),
        migrations.AlterField(
            model_name='pack',
            name='hora_dia3',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Hora día 3', null=True),
        ),
    ]
