# Generated by Django 5.2.11 on 2026-06-26 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0009_pack_hora_dia4_alter_pack_frecuencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='hora_dia5',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Hora día 5', null=True),
        ),
        migrations.AlterField(
            model_name='pack',
            name='tipo',
            field=models.CharField(choices=[('PACK12', 'Pack 12 Clases'), ('PACK10', 'Pack 10 Clases'), ('PACK8', 'Pack 8 Clases'), ('PACK4', 'Pack 4 Clases'), ('REDUCIDO', 'Pack Reducido (2–9 clases) — legacy'), ('SUELTA', 'Clase Suelta'), ('PRUEBA', 'Clase de Prueba'), ('PRIVADA', 'Clase Privada'), ('BB_FULL', 'Body Balance Mensualidad'), ('BB_SEMANAL', 'Body Balance Clase Semanal')], max_length=20),
        ),
    ]
