# Generated by Django 5.2.11 on 2026-07-03 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0010_pack_hora_dia5_alter_pack_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='pares_json',
            field=models.JSONField(blank=True, help_text='Pares fecha/hora para PACK4 y BB_FULL — respaldo si la sesión se pierde', null=True),
        ),
    ]
