# Generated by Django 5.2.11 on 2026-08-27 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0011_pack_pares_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='tipo',
            field=models.CharField(choices=[('PACK12', 'Pack 12 Clases'), ('PACK10', 'Pack 10 Clases'), ('PACK8', 'Pack 8 Clases'), ('PACK4', 'Pack 4 Clases'), ('REDUCIDO', 'Pack Reducido (2–9 clases) — legacy'), ('SUELTA', 'Clase Suelta'), ('PRUEBA', 'Clase de Prueba'), ('PRIVADA', 'Clase Privada'), ('BB_FULL', 'Body Balance Mensualidad'), ('BB_SEMANAL', 'Body Balance Clase Semanal'), ('BB_SEMANAL_2', 'Body Balance 2 veces por semana')], max_length=20),
        ),
    ]
